### ISSUE TITLE
Proposal approved without the required votes

### ISSUE THREAD

**Issue by lock9** [AxLabs/grantshares#38]
The proposal Analysis of Two tokens on Neo Economy had 3 votes and was approved. It needed 4.

![image](https://user-images.githubusercontent.com/38396062/201444300-fbe955bb-392c-4962-920e-12b836d7acff.png)

**Comment by gsmachado** [comment]
@lock9 thanks for opening an issue. 👍 

This is a valid question, but it seems that the "abstention" mechanism is little or not understood by the majority of people.

Go to our new "Parameters" page: https://grantshares.io/app/parameters

There, read the sections "Default and Minimum Acceptance Rate" and "Default and Minimum Quorum".

Basically, how this thing works is as follows: abstention counts in the quorum, and the minimum acceptance rate is based on ALL casted votes.

In this case, if the proposal had 3 members casting "abstain" and 3 members casting "accept", the proposal would be rejected. But, since this particular proposal had 3 members casting "accept" and 2 members casting "abstain", the proposal reached the minimum quorum (5 members should cast) and >50% explicitly voted to accept the proposal -- resulting in the accepted state.

@csmuller, please go ahead and add any explanation if I'm missing something.

@lock9 If you don't have any other questions about this specific subject please close the issue. Thanks!

**Comment by lock9** [comment]
That doesn't make any sense, but I don't care.

**Comment by gsmachado** [comment]
@lock9 This system is not something new. We didn't come up with this out of the blue, i.e., we didn't reinvent the wheel. 😄 

For example:

> _Abstentions do not count in tallying the vote negatively or positively; when members abstain, they are in effect attending only to contribute to a [quorum](https://en.wikipedia.org/wiki/Quorum)._
>     -- Abstention. (2022, October 6). In Wikipedia. https://en.wikipedia.org/wiki/Abstention

You can read about it in other places as well.

But, yes, we have some changes to be made on the endorsement part in order to exclude the min. quorum variable. We're still debating about this change, though.

We'd be curious to know your ARGUMENTS about what you wrote:

> That doesn't make any sense, but I don't care.

@lock9 so, can you point us out why it doesn't make _any_ sense?

**Comment by lock9** [comment]
...

**Comment by gsmachado** [comment]
Just for documentation purposes:

@lock9 I believe you're confusing concepts and mixing things up.

Indeed, abstention must be contrasted with blank votes. Right.
BUT, there's no way to take abstentions into account without a transaction.

Again, taken [from the article](https://en.wikipedia.org/wiki/Abstention):

> when members abstain, they are in effect attending only to contribute to a quorum.

In summary: abstentions (as a tx) should not count in the final acceptance BUT should contribute to a quorum. 😄

**Comment by edgedlt** [comment]
Not endorsing Rick's attitude here, but I do understand where he is coming from.

A majority vote between 50 people requires 26 votes. If 10 of those voters abstained, the total number of voters is decreased to 40, and the majority required among remaining voters becomes 21. The abstains are still contributing to quorum. They are doing so by lowering the threshold to pass the motion. But their impact on the result is halved: 10 abstains only decreases the pass threshold by 5 votes.

Applying the above to the case in question, we had 9 voting members and two abstains, so the vote result would be 3/7. Since the current mechanism is essentially considering the abstain as a full vote, rather than accounting for its reduced impact, it pushed this proposal over the edge.

I think I would agree with Rick that it's more intuitive for abstention to reduce the size of the voter pool. As is, abstention is no different from a yes vote in terms of its impact on an outcome.

Side note: This proposal was an edge case. With better voter participation, we wouldn't have encountered it so early, so I think addressing that should remain our primary concern.

**Comment by gsmachado** [comment]
@EdgeDLT sure, I agree with you and your reasoning. 👍 

But, that's how things work now in GrantShares. This governance model was shown and agreed upon in several meetings with the members.

The good news is: what we're working on, right now, is to slightly change the dynamic of the endorser/endorsement and remove the necessity for a min. quorum. Then, it's debatable if we should remove the "abstention" voting type, but I would keep it to demonstrate that a member is "aware" of the proposal -- but simply can't (or doesn't want to) express an opinion.

We're still working on the concept. More details to come in the coming weeks/end-of-year. 😄

**Comment by lock9** [comment]
Hello,
I am writing to apologize for my recently displayed aggressive and shameful behavior. Nothing justifies this kind of attitude, even if I strongly disagree with something.
Out of all the communities we have in the ecosystem, AxLabs is probably the most professional. There is attention to detail, good designs, documentation, support, and constant maintenance.
I got triggered because you added the 'question' label'. I apologize for offending you for such futile reasons, AxLabs, or anyone else, shouldn't have to deal with these messages.
